### ISSUE TITLE
Clarify that certain variables stand for arbitrary terms

### ISSUE THREAD

**Issue by javierdiaz72** [input-output-hk/equivalence-reasoner#27]
The usage documentation currently states that conditional rewrite rules should have the form `P⇩1 ⟹ ⋯ ⟹ P⇩n ⟹ S x y`, where `x` and `y` are intended to denote arbitrary terms. However, the notation used might mislead the user into believing that `x` and `y` denote free variables instead. We shall improve the documentation to clarify that `x` and `y` are intended to denote arbitrary terms. Note that, following the notation used in the Isabelle/Isar Reference Manual, I think we could write `S t⇩1 t⇩2` instead.

**Comment by jeltsch** [comment]
Note that this doesn’t just apply to the `x` and the `y` in the prototypical conditional rewrite rule. In fact, also the `P⇩i` and the `S` can be arbitrary terms in principle, and also in other places where the documentation talks about “shapes” we have this issue: “facts of the shape `T ≤ U`” and “those premises that are of the shape `S ≤ T`”. I didn’t want to write explicitly for all these variables that they denote terms, because I thought this would have made the text hard to read.

**Comment by javierdiaz72** [comment]
> Note that this doesn’t just apply to the `x` and the `y` in the prototypical conditional rewrite rule. In fact, also the `P⇩i` and the `S` can be arbitrary terms in principle, and also in other places where the documentation talks about “shapes” we have this issue: “facts of the shape `T ≤ U`” and “those premises that are of the shape `S ≤ T`”. I didn’t want to write explicitly for all these variables that they denote terms, because I thought this would have made the text hard to read.

You're absolutely right. I think a good approach is to search the [Isabelle/Isar Reference Manual](https://isabelle.in.tum.de/dist/Isabelle2021-1/doc/isar-ref.pdf) for a situation similar to ours and see how it's resolved.

**Comment by javierdiaz72** [comment]
I finished searching the Isabelle/Isar Reference Manual for a situation similar to ours and see how it’s resolved. Here's my findings:

I found places where they used the syntax `t⇩1`, `t⇩2`, etc. as placeholders for terms, for example `where x⇩1 = t⇩1 and ... x⇩n = t⇩n"` (definition of `where`, page 152). Furthermore, in other places, for example `⋀x. B(x)` (syntax of Isabelle/Pure, page 29), `B` seems not to mean an application of an arbitrary term to the variable `x`, but an arbitrary term that may contain `x`, that is, a kind of higher-order meta-variable, standing for a “single-hole context”.

As a conclusion, it seems that the authors of the Reference Manual basically follow our approach: They use ordinary identifiers also as meta-variables, standing for arbitrary terms. They even used them as higher-order meta-variables, standing for terms with holes. The only twist seems to be that they avoid using `x` and possibly `y`, optionally with subscripts, as meta-variables, but used them only as Isabelle variables, choosing `t⇩1` and `t⇩2` as meta-variables instead. However, this twist seems to apply only to generic situations. Where they talk about specific kinds of terms, for example propositions, they seem to use identifiers that fit the kind of terms, for example `B`, so that the same identifiers may get used for Isabelle variables and meta-variables.
Following their approach would then mean that we replace `x` and `y` in the shape of a conditional rewrite rule by `t⇩1` and `t⇩2`, but otherwise keep our current meta-variables.

**Comment by jeltsch** [comment]
Thanks a lot for this detailed investigation and report.

I think I’ll just replace `x` and `y` in the shape of conditional rewrite rules by `t⇩1` and `t⇩2` and leave everything else as it is. There are places where you could argue a replacement was warranted as well, for example, in the following sentence:

> A term `canonical R x` denotes a value that is equivalent to `x` with respect to `R` and serves as a canonical form of all values that are equivalent to `x`.

Here, `x` stands for arbitrary *values*, which could be represented by arbitrary *terms*. However, this sentence is mostly a definition, and in a formal definition you would use Isabelle variables as function arguments. On the other hand, where we mention the shape of conditional rewrite rules we talk about term rewriting and thus specifically about terms instead of just the values they denote.
